modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="nodami"
version="${file.jarVersion}"
displayName="No Damage Immunity(NoDamI) Reload Mod"
authors="Mirkiri"
description=''' '''
[[dependencies.nodami]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nodami]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
